Group assignment of default values to single step

diff --git a/install/action.yml b/install/action.yml
--- a/install/action.yml
+++ b/install/action.yml
@@ -18,6 +18,10 @@ inputs:
     description: |
       Argument to pass to `pip install`. If empty (default), it will be determined automatically
     default: ''
+  repo-full-name:
+    required: false
+    description: Full name (i.e. user/repo) of the repository to install
+    default: watertap-org/watertap
   ref-to-install:
     required: false
     description: |
@@ -30,7 +34,7 @@ inputs:
 outputs:
   target:
     description: Installation target
-    value: ${{ inputs.target || steps.determine-target.outputs.target }}
+    value: ${{ steps.assign.outputs.target }}
 runs:
   using: composite
   steps:
@@ -45,43 +49,51 @@ runs:
       with:
         activate-environment: watertap-dev
         python-version: ${{ inputs.python-version }}
-    - name: Determine install target
-      id: determine-target
-      if: inputs.target == ''
+    - name: Assign values (dynamically and/or from inputs)
+      id: assign
       shell: bash -l {0}
       env:
+        _target: ${{ inputs.target }}
         _variant: ${{ inputs.variant }}
-        _repo_full_name: ${{ github.event.pull_request && github.event.pull_request.head.repo.full_name || 'watertap-org/watertap' }}
+        _repo_full_name: ${{ github.event.pull_request && github.event.pull_request.head.repo.full_name || inputs.repo-full-name }}
         _ref_to_install: ${{ github.event_pull_request && github.event.pull_request.head.sha || inputs.ref-to-install }}
       run: |
-        case "$_variant" in
-            editable)
-                _target="-r requirements-dev.txt"
-                ;;
-            noneditable)
-                _install_url="https://github.com/${_repo_full_name}/archive/${_ref_to_install}.zip"
-                _target="watertap @ $_install_url"
-                ;;
-            *)
-                echo "Invalid value: $_variant"
-                exit 1
-                ;;
-        esac
+        if [ -z "$_target" ] ; then
+            case "$_variant" in
+                editable)
+                    _target="-r requirements-dev.txt"
+                    ;;
+                noneditable)
+                    _install_url="https://github.com/${_repo_full_name}/archive/${_ref_to_install}.zip"
+                    _target="watertap @ $_install_url"
+                    ;;
+                *)
+                    echo "Invalid value: $_variant"
+                    exit 1
+                    ;;
+            esac
+        fi
         echo "::set-output name=target::$_target"
+        echo "::set-output name=repo-full-name::$_repo_full_name"
+        echo "::set-output name=ref-to-install::$_ref_to_install"
+        echo "::set-output name=solver-dependencies::${{ inputs.solver-dependencies }}"
     - name: Checkout source
       if: inputs.variant == 'editable'
       uses: actions/checkout@v2
+      with:
+        repository: ${{ steps.assign.outputs.repo-full-name }}
+        ref: ${{ steps.assign.outputs.ref-to-install }}
     - name: Install package with dependencies
       shell: bash -l {0}
       run: |
-        pip install --progress-bar off -r "${{ inputs.target || steps.determine-target.outputs.target }}"
+        pip install --progress-bar off "${{ steps.assign.outputs.target }}"
     - name: Install solver dependencies (IDAES extensions)
-      if: inputs.solver-dependencies == 'idaes-ext'
+      if: steps.assign.outputs.solver-dependencies == 'idaes-ext'
       shell: bash -l {0}
       run: |
         idaes get-extensions --verbose
     - name: Install solver dependencies (fallback, conda-forge + Pyomo)
-      if: inputs.solver-dependencies != 'idaes-ext'
+      if: steps.assign.outputs.solver-dependencies != 'idaes-ext'
       shell: bash -l {0}
       run: |
         conda install --quiet --yes -c conda-forge ipopt cmake
